services:
  django:
    build: .
    image: blasphemy_django
    container_name: blasphemy_django
    volumes:
      - .:/code
    env_file: .env
    working_dir: /code/src
    command: python manage.py runserver 0:8000
    ports:
      - "${DJANGO_HOST_FORWARD_PORT:-8000}:8000"
    stdin_open: true
    tty: true
    depends_on:
      - db
      - mailpit
      - redis

  db:
    env_file: .env
    image: postgres:16.3-alpine3.20
    container_name: blasphemy_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
      PGPORT: ${POSTGRES_DB_PORT}
    ports:
      - "${POSTGRES_HOST_FORWARD_PORT}:${POSTGRES_DB_PORT}"
    volumes:
      - dbdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:v1.19.1
    container_name: blasphemy_mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
    volumes:
      - mailpit-data:/data

  redis:
    env_file: .env
    image: redis:7.2.5-alpine3.20
    container_name: blasphemy_redis
    ports:
      # TODO: Check if internal port is configurable
      - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redis-data:/data

  celery_workers:
    build: .
    image: blasphemy_celery_workers
    container_name: blasphemy_celery_workers
    volumes:
      - .:/code
    env_file: .env
    working_dir: /code/src
    command: celery -A core.celery worker -E -l info
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  celery_beat:
    build: .
    image: blasphemy_celery_beat
    container_name: blasphemy_celery_beat
    volumes:
      - .:/code
    env_file: .env
    working_dir: /code/src
    command: celery -A core.celery beat -l info
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  celery_flower:
    build: .
    image: blasphemy_celery_flower
    volumes:
      - .:/code
    env_file: .env
    working_dir: /code/src
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  dbdata:
    driver: local
  mailpit-data:
    driver: local
  redis-data:
    driver: local
