import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = ()

    operations = (
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=128)),
                ("code", models.TextField()),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("ABAP", "abap"),
                            ("AMDGPU", "amdgpu"),
                            ("APL", "apl"),
                            ("ABNF", "abnf"),
                            ("ActionScript 3", "actionscript3"),
                            ("ActionScript", "actionscript"),
                            ("Ada", "ada"),
                            ("ADL", "adl"),
                            ("Agda", "agda"),
                            ("Aheui", "aheui"),
                            ("Alloy", "alloy"),
                            ("AmbientTalk", "ambienttalk"),
                            ("Ampl", "ampl"),
                            ("HTML + Angular2", "html+ng2"),
                            ("Angular2", "ng2"),
                            ("ANTLR With ActionScript Target", "antlr-actionscript"),
                            ("ANTLR With C# Target", "antlr-csharp"),
                            ("ANTLR With CPP Target", "antlr-cpp"),
                            ("ANTLR With Java Target", "antlr-java"),
                            ("ANTLR", "antlr"),
                            ("ANTLR With ObjectiveC Target", "antlr-objc"),
                            ("ANTLR With Perl Target", "antlr-perl"),
                            ("ANTLR With Python Target", "antlr-python"),
                            ("ANTLR With Ruby Target", "antlr-ruby"),
                            ("ApacheConf", "apacheconf"),
                            ("AppleScript", "applescript"),
                            ("Arduino", "arduino"),
                            ("Arrow", "arrow"),
                            ("Arturo", "arturo"),
                            ("ASCII armored", "asc"),
                            ("ASN.1", "asn1"),
                            ("AspectJ", "aspectj"),
                            ("Asymptote", "asymptote"),
                            ("Augeas", "augeas"),
                            ("AutoIt", "autoit"),
                            ("autohotkey", "autohotkey"),
                            ("Awk", "awk"),
                            ("BBC Basic", "bbcbasic"),
                            ("BBCode", "bbcode"),
                            ("BC", "bc"),
                            ("BQN", "bqn"),
                            ("BST", "bst"),
                            ("BARE", "bare"),
                            ("Base Makefile", "basemake"),
                            ("Bash", "bash"),
                            ("Bash Session", "console"),
                            ("Batchfile", "batch"),
                            ("Bdd", "bdd"),
                            ("Befunge", "befunge"),
                            ("Berry", "berry"),
                            ("BibTeX", "bibtex"),
                            ("BlitzBasic", "blitzbasic"),
                            ("BlitzMax", "blitzmax"),
                            ("Blueprint", "blueprint"),
                            ("BNF", "bnf"),
                            ("Boa", "boa"),
                            ("Boo", "boo"),
                            ("Boogie", "boogie"),
                            ("Brainfuck", "brainfuck"),
                            ("BUGS", "bugs"),
                            ("CAmkES", "camkes"),
                            ("C", "c"),
                            ("CMake", "cmake"),
                            ("c-objdump", "c-objdump"),
                            ("CPSA", "cpsa"),
                            ("CSS+UL4", "css+ul4"),
                            ("aspx-cs", "aspx-cs"),
                            ("C#", "csharp"),
                            ("ca65 assembler", "ca65"),
                            ("cADL", "cadl"),
                            ("CapDL", "capdl"),
                            ("Cap'n Proto", "capnp"),
                            ("Carbon", "carbon"),
                            ("CBM BASIC V2", "cbmbas"),
                            ("CDDL", "cddl"),
                            ("Ceylon", "ceylon"),
                            ("CFEngine3", "cfengine3"),
                            ("ChaiScript", "chaiscript"),
                            ("Chapel", "chapel"),
                            ("Charmci", "charmci"),
                            ("HTML+Cheetah", "html+cheetah"),
                            ("JavaScript+Cheetah", "javascript+cheetah"),
                            ("Cheetah", "cheetah"),
                            ("XML+Cheetah", "xml+cheetah"),
                            ("Cirru", "cirru"),
                            ("Clay", "clay"),
                            ("Clean", "clean"),
                            ("Clojure", "clojure"),
                            ("ClojureScript", "clojurescript"),
                            ("COBOLFree", "cobolfree"),
                            ("COBOL", "cobol"),
                            ("CoffeeScript", "coffeescript"),
                            ("Coldfusion CFC", "cfc"),
                            ("Coldfusion HTML", "cfm"),
                            ("cfstatement", "cfs"),
                            ("COMAL-80", "comal"),
                            ("Common Lisp", "common-lisp"),
                            ("Component Pascal", "componentpascal"),
                            ("Coq", "coq"),
                            ("cplint", "cplint"),
                            ("C++", "cpp"),
                            ("cpp-objdump", "cpp-objdump"),
                            ("Crmsh", "crmsh"),
                            ("Croc", "croc"),
                            ("Cryptol", "cryptol"),
                            ("Crystal", "cr"),
                            ("Csound Document", "csound-document"),
                            ("Csound Orchestra", "csound"),
                            ("Csound Score", "csound-score"),
                            ("CSS+Django/Jinja", "css+django"),
                            ("CSS+Ruby", "css+ruby"),
                            ("CSS+Genshi Text", "css+genshitext"),
                            ("CSS", "css"),
                            ("CSS+PHP", "css+php"),
                            ("CSS+Smarty", "css+smarty"),
                            ("CUDA", "cuda"),
                            ("Cypher", "cypher"),
                            ("Cython", "cython"),
                            ("D", "d"),
                            ("d-objdump", "d-objdump"),
                            ("Darcs Patch", "dpatch"),
                            ("Dart", "dart"),
                            ("DASM16", "dasm16"),
                            ("Dax", "dax"),
                            ("Debian Control file", "debcontrol"),
                            ("Delphi", "delphi"),
                            ("Desktop file", "desktop"),
                            ("Devicetree", "devicetree"),
                            ("dg", "dg"),
                            ("Diff", "diff"),
                            ("Django/Jinja", "django"),
                            ("Zone", "zone"),
                            ("Docker", "docker"),
                            ("DTD", "dtd"),
                            ("Duel", "duel"),
                            ("Dylan session", "dylan-console"),
                            ("Dylan", "dylan"),
                            ("DylanLID", "dylan-lid"),
                            ("ECL", "ecl"),
                            ("eC", "ec"),
                            ("Earl Grey", "earl-grey"),
                            ("Easytrieve", "easytrieve"),
                            ("EBNF", "ebnf"),
                            ("Eiffel", "eiffel"),
                            ("Elixir iex session", "iex"),
                            ("Elixir", "elixir"),
                            ("Elm", "elm"),
                            ("Elpi", "elpi"),
                            ("EmacsLisp", "emacs-lisp"),
                            ("E-mail", "email"),
                            ("ERB", "erb"),
                            ("Erlang", "erlang"),
                            ("Erlang erl session", "erl"),
                            ("HTML+Evoque", "html+evoque"),
                            ("Evoque", "evoque"),
                            ("XML+Evoque", "xml+evoque"),
                            ("execline", "execline"),
                            ("Ezhil", "ezhil"),
                            ("F#", "fsharp"),
                            ("FStar", "fstar"),
                            ("Factor", "factor"),
                            ("Fancy", "fancy"),
                            ("Fantom", "fan"),
                            ("Felix", "felix"),
                            ("Fennel", "fennel"),
                            ("Fift", "fift"),
                            ("Fish", "fish"),
                            ("Flatline", "flatline"),
                            ("FloScript", "floscript"),
                            ("Forth", "forth"),
                            ("FortranFixed", "fortranfixed"),
                            ("Fortran", "fortran"),
                            ("FoxPro", "foxpro"),
                            ("Freefem", "freefem"),
                            ("FunC", "func"),
                            ("Futhark", "futhark"),
                            ("GAP session", "gap-console"),
                            ("GAP", "gap"),
                            ("GDScript", "gdscript"),
                            ("GLSL", "glsl"),
                            ("GSQL", "gsql"),
                            ("GAS", "gas"),
                            ("g-code", "gcode"),
                            ("Genshi", "genshi"),
                            ("Genshi Text", "genshitext"),
                            ("Gettext Catalog", "pot"),
                            ("Gherkin", "gherkin"),
                            ("Gnuplot", "gnuplot"),
                            ("Go", "go"),
                            ("Golo", "golo"),
                            ("GoodData-CL", "gooddata-cl"),
                            ("Gosu", "gosu"),
                            ("Gosu Template", "gst"),
                            ("GraphQL", "graphql"),
                            ("Graphviz", "graphviz"),
                            ("Groff", "groff"),
                            ("Groovy", "groovy"),
                            ("HLSL", "hlsl"),
                            ("HTML+UL4", "html+ul4"),
                            ("Haml", "haml"),
                            ("HTML+Handlebars", "html+handlebars"),
                            ("Handlebars", "handlebars"),
                            ("Haskell", "haskell"),
                            ("Haxe", "haxe"),
                            ("Hexdump", "hexdump"),
                            ("HSAIL", "hsail"),
                            ("Hspec", "hspec"),
                            ("HTML+Django/Jinja", "html+django"),
                            ("HTML+Genshi", "html+genshi"),
                            ("HTML", "html"),
                            ("HTML+PHP", "html+php"),
                            ("HTML+Smarty", "html+smarty"),
                            ("HTTP", "http"),
                            ("Hxml", "haxeml"),
                            ("Hy", "hylang"),
                            ("Hybris", "hybris"),
                            ("IDL", "idl"),
                            ("Icon", "icon"),
                            ("Idris", "idris"),
                            ("Igor", "igor"),
                            ("Inform 6", "inform6"),
                            ("Inform 6 template", "i6t"),
                            ("Inform 7", "inform7"),
                            ("INI", "ini"),
                            ("Io", "io"),
                            ("Ioke", "ioke"),
                            ("IRC logs", "irc"),
                            ("Isabelle", "isabelle"),
                            ("J", "j"),
                            ("JMESPath", "jmespath"),
                            ("JSLT", "jslt"),
                            ("JAGS", "jags"),
                            ("Jasmin", "jasmin"),
                            ("Java", "java"),
                            ("JavaScript+Django/Jinja", "javascript+django"),
                            ("JavaScript+Ruby", "javascript+ruby"),
                            ("JavaScript+Genshi Text", "js+genshitext"),
                            ("JavaScript", "javascript"),
                            ("JavaScript+PHP", "javascript+php"),
                            ("JavaScript+Smarty", "javascript+smarty"),
                            ("Javascript+UL4", "js+ul4"),
                            ("JCL", "jcl"),
                            ("JSGF", "jsgf"),
                            ("JSONBareObject", "jsonbareobject"),
                            ("JSON-LD", "jsonld"),
                            ("JSON", "json"),
                            ("Jsonnet", "jsonnet"),
                            ("Java Server Page", "jsp"),
                            ("JSX", "jsx"),
                            ("Julia console", "jlcon"),
                            ("Julia", "julia"),
                            ("Juttle", "juttle"),
                            ("K", "k"),
                            ("Kal", "kal"),
                            ("Kconfig", "kconfig"),
                            ("Kernel log", "kmsg"),
                            ("Koka", "koka"),
                            ("Kotlin", "kotlin"),
                            ("Kuin", "kuin"),
                            ("Kusto", "kql"),
                            ("LSL", "lsl"),
                            ("CSS+Lasso", "css+lasso"),
                            ("HTML+Lasso", "html+lasso"),
                            ("JavaScript+Lasso", "javascript+lasso"),
                            ("Lasso", "lasso"),
                            ("XML+Lasso", "xml+lasso"),
                            ("LDAP configuration file", "ldapconf"),
                            ("LDIF", "ldif"),
                            ("Lean", "lean"),
                            ("LessCss", "less"),
                            ("Lighttpd configuration file", "lighttpd"),
                            ("LilyPond", "lilypond"),
                            ("Limbo", "limbo"),
                            ("liquid", "liquid"),
                            ("Literate Agda", "literate-agda"),
                            ("Literate Cryptol", "literate-cryptol"),
                            ("Literate Haskell", "literate-haskell"),
                            ("Literate Idris", "literate-idris"),
                            ("LiveScript", "livescript"),
                            ("LLVM", "llvm"),
                            ("LLVM-MIR Body", "llvm-mir-body"),
                            ("LLVM-MIR", "llvm-mir"),
                            ("Logos", "logos"),
                            ("Logtalk", "logtalk"),
                            ("Lua", "lua"),
                            ("MCFunction", "mcfunction"),
                            ("MCSchema", "mcschema"),
                            ("MIME", "mime"),
                            ("MIPS", "mips"),
                            ("MOOCode", "moocode"),
                            ("MSDOS Session", "doscon"),
                            ("Macaulay2", "macaulay2"),
                            ("Makefile", "make"),
                            ("CSS+Mako", "css+mako"),
                            ("HTML+Mako", "html+mako"),
                            ("JavaScript+Mako", "javascript+mako"),
                            ("Mako", "mako"),
                            ("XML+Mako", "xml+mako"),
                            ("MAQL", "maql"),
                            ("Markdown", "markdown"),
                            ("Mask", "mask"),
                            ("Mason", "mason"),
                            ("Mathematica", "mathematica"),
                            ("Matlab", "matlab"),
                            ("Matlab session", "matlabsession"),
                            ("Maxima", "maxima"),
                            ("Meson", "meson"),
                            ("MiniD", "minid"),
                            ("MiniScript", "miniscript"),
                            ("Modelica", "modelica"),
                            ("Modula-2", "modula2"),
                            ("MoinMoin/Trac Wiki markup", "trac-wiki"),
                            ("Monkey", "monkey"),
                            ("Monte", "monte"),
                            ("MoonScript", "moonscript"),
                            ("Mosel", "mosel"),
                            ("CSS+mozpreproc", "css+mozpreproc"),
                            ("mozhashpreproc", "mozhashpreproc"),
                            ("Javascript+mozpreproc", "javascript+mozpreproc"),
                            ("mozpercentpreproc", "mozpercentpreproc"),
                            ("XUL+mozpreproc", "xul+mozpreproc"),
                            ("MQL", "mql"),
                            ("Mscgen", "mscgen"),
                            ("MuPAD", "mupad"),
                            ("MXML", "mxml"),
                            ("MySQL", "mysql"),
                            ("CSS+Myghty", "css+myghty"),
                            ("HTML+Myghty", "html+myghty"),
                            ("JavaScript+Myghty", "javascript+myghty"),
                            ("Myghty", "myghty"),
                            ("XML+Myghty", "xml+myghty"),
                            ("NCL", "ncl"),
                            ("NSIS", "nsis"),
                            ("NASM", "nasm"),
                            ("objdump-nasm", "objdump-nasm"),
                            ("Nemerle", "nemerle"),
                            ("nesC", "nesc"),
                            ("NestedText", "nestedtext"),
                            ("NewLisp", "newlisp"),
                            ("Newspeak", "newspeak"),
                            ("Nginx configuration file", "nginx"),
                            ("Nimrod", "nimrod"),
                            ("Nit", "nit"),
                            ("Nix", "nixos"),
                            ("Node.js REPL console session", "nodejsrepl"),
                            ("Notmuch", "notmuch"),
                            ("NuSMV", "nusmv"),
                            ("NumPy", "numpy"),
                            ("objdump", "objdump"),
                            ("Objective-C", "objective-c"),
                            ("Objective-C++", "objective-c++"),
                            ("Objective-J", "objective-j"),
                            ("OCaml", "ocaml"),
                            ("Octave", "octave"),
                            ("ODIN", "odin"),
                            ("OMG Interface Definition Language", "omg-idl"),
                            ("Ooc", "ooc"),
                            ("Opa", "opa"),
                            ("OpenEdge ABL", "openedge"),
                            ("OpenSCAD", "openscad"),
                            ("Text output", "output"),
                            ("PacmanConf", "pacmanconf"),
                            ("Pan", "pan"),
                            ("ParaSail", "parasail"),
                            ("Pawn", "pawn"),
                            ("PEG", "peg"),
                            ("Perl6", "perl6"),
                            ("Perl", "perl"),
                            ("Phix", "phix"),
                            ("PHP", "php"),
                            ("Pig", "pig"),
                            ("Pike", "pike"),
                            ("PkgConfig", "pkgconfig"),
                            ("PL/pgSQL", "plpgsql"),
                            ("Pointless", "pointless"),
                            ("Pony", "pony"),
                            ("Portugol", "portugol"),
                            ("PostScript", "postscript"),
                            ("PostgreSQL console (psql)", "psql"),
                            ("PostgreSQL EXPLAIN dialect", "postgres-explain"),
                            ("PostgreSQL SQL dialect", "postgresql"),
                            ("POVRay", "pov"),
                            ("PowerShell", "powershell"),
                            ("PowerShell Session", "pwsh-session"),
                            ("Praat", "praat"),
                            ("Procfile", "procfile"),
                            ("Prolog", "prolog"),
                            ("PromQL", "promql"),
                            ("Properties", "properties"),
                            ("Protocol Buffer", "protobuf"),
                            ("PRQL", "prql"),
                            ("PsySH console session for PHP", "psysh"),
                            ("PTX", "ptx"),
                            ("Pug", "pug"),
                            ("Puppet", "puppet"),
                            ("PyPy Log", "pypylog"),
                            ("Python 2.x", "python2"),
                            ("Python 2.x Traceback", "py2tb"),
                            ("Python console session", "pycon"),
                            ("Python", "python"),
                            ("Python Traceback", "pytb"),
                            ("Python+UL4", "py+ul4"),
                            ("QBasic", "qbasic"),
                            ("Q", "q"),
                            ("QVTO", "qvto"),
                            ("Qlik", "qlik"),
                            ("QML", "qml"),
                            ("RConsole", "rconsole"),
                            ("Relax-NG Compact", "rng-compact"),
                            ("RPMSpec", "spec"),
                            ("Racket", "racket"),
                            ("Ragel in C Host", "ragel-c"),
                            ("Ragel in CPP Host", "ragel-cpp"),
                            ("Ragel in D Host", "ragel-d"),
                            ("Embedded Ragel", "ragel-em"),
                            ("Ragel in Java Host", "ragel-java"),
                            ("Ragel", "ragel"),
                            ("Ragel in Objective C Host", "ragel-objc"),
                            ("Ragel in Ruby Host", "ragel-ruby"),
                            ("Raw token data", "raw token data"),
                            ("Rd", "rd"),
                            ("ReasonML", "reasonml"),
                            ("REBOL", "rebol"),
                            ("Red", "red"),
                            ("Redcode", "redcode"),
                            ("reg", "registry"),
                            ("ResourceBundle", "resourcebundle"),
                            ("Rexx", "rexx"),
                            ("RHTML", "rhtml"),
                            ("Ride", "ride"),
                            ("Rita", "rita"),
                            ("Roboconf Graph", "roboconf-graph"),
                            ("Roboconf Instances", "roboconf-instances"),
                            ("RobotFramework", "robotframework"),
                            ("RQL", "rql"),
                            ("RSL", "rsl"),
                            ("reStructuredText", "restructuredtext"),
                            ("TrafficScript", "trafficscript"),
                            ("Ruby irb session", "rbcon"),
                            ("Ruby", "ruby"),
                            ("Rust", "rust"),
                            ("SAS", "sas"),
                            ("S", "splus"),
                            ("Standard ML", "sml"),
                            ("SNBT", "snbt"),
                            ("SARL", "sarl"),
                            ("Sass", "sass"),
                            ("Savi", "savi"),
                            ("Scala", "scala"),
                            ("Scaml", "scaml"),
                            ("scdoc", "scdoc"),
                            ("Scheme", "scheme"),
                            ("Scilab", "scilab"),
                            ("SCSS", "scss"),
                            ("Sed", "sed"),
                            ("ShExC", "shexc"),
                            ("Shen", "shen"),
                            ("Sieve", "sieve"),
                            ("Silver", "silver"),
                            ("Singularity", "singularity"),
                            ("Slash", "slash"),
                            ("Slim", "slim"),
                            ("Slurm", "slurm"),
                            ("Smali", "smali"),
                            ("Smalltalk", "smalltalk"),
                            ("SmartGameFormat", "sgf"),
                            ("Smarty", "smarty"),
                            ("Smithy", "smithy"),
                            ("Snobol", "snobol"),
                            ("Snowball", "snowball"),
                            ("Solidity", "solidity"),
                            ("Sophia", "sophia"),
                            ("SourcePawn", "sp"),
                            ("Debian Sourcelist", "debsources"),
                            ("SPARQL", "sparql"),
                            ("Spice", "spice"),
                            ("SQL+Jinja", "sql+jinja"),
                            ("SQL", "sql"),
                            ("sqlite3con", "sqlite3"),
                            ("SquidConf", "squidconf"),
                            ("Srcinfo", "srcinfo"),
                            ("Scalate Server Page", "ssp"),
                            ("Stan", "stan"),
                            ("Stata", "stata"),
                            ("SuperCollider", "supercollider"),
                            ("Swift", "swift"),
                            ("SWIG", "swig"),
                            ("systemverilog", "systemverilog"),
                            ("Systemd", "systemd"),
                            ("TAP", "tap"),
                            ("Typographic Number Theory", "tnt"),
                            ("TOML", "toml"),
                            ("TADS 3", "tads3"),
                            ("Tal", "tal"),
                            ("TASM", "tasm"),
                            ("Tcl", "tcl"),
                            ("Tcsh", "tcsh"),
                            ("Tcsh Session", "tcshcon"),
                            ("Tea", "tea"),
                            ("teal", "teal"),
                            ("Tera Term macro", "teratermmacro"),
                            ("Termcap", "termcap"),
                            ("Terminfo", "terminfo"),
                            ("Terraform", "terraform"),
                            ("TeX", "tex"),
                            ("Text only", "text"),
                            ("ThingsDB", "ti"),
                            ("Thrift", "thrift"),
                            ("tiddler", "tid"),
                            ("Tl-b", "tlb"),
                            ("TLS Presentation Language", "tls"),
                            ("Todotxt", "todotxt"),
                            ("Transact-SQL", "tsql"),
                            ("Treetop", "treetop"),
                            ("Turtle", "turtle"),
                            ("HTML+Twig", "html+twig"),
                            ("Twig", "twig"),
                            ("TypeScript", "typescript"),
                            ("TypoScriptCssData", "typoscriptcssdata"),
                            ("TypoScriptHtmlData", "typoscripthtmldata"),
                            ("TypoScript", "typoscript"),
                            ("UL4", "ul4"),
                            ("ucode", "ucode"),
                            ("Unicon", "unicon"),
                            ("Unix/Linux config files", "unixconfig"),
                            ("UrbiScript", "urbiscript"),
                            ("urlencoded", "urlencoded"),
                            ("USD", "usd"),
                            ("VBScript", "vbscript"),
                            ("VCL", "vcl"),
                            ("VCLSnippets", "vclsnippets"),
                            ("VCTreeStatus", "vctreestatus"),
                            ("VGL", "vgl"),
                            ("Vala", "vala"),
                            ("aspx-vb", "aspx-vb"),
                            ("VB.net", "vb.net"),
                            ("HTML+Velocity", "html+velocity"),
                            ("Velocity", "velocity"),
                            ("XML+Velocity", "xml+velocity"),
                            ("Verifpal", "verifpal"),
                            ("verilog", "verilog"),
                            ("vhdl", "vhdl"),
                            ("VimL", "vim"),
                            ("Visual Prolog Grammar", "visualprologgrammar"),
                            ("Visual Prolog", "visualprolog"),
                            ("Vyper", "vyper"),
                            ("WDiff", "wdiff"),
                            ("WebAssembly", "wast"),
                            ("Web IDL", "webidl"),
                            ("WebGPU Shading Language", "wgsl"),
                            ("Whiley", "whiley"),
                            ("Wikitext", "wikitext"),
                            ("World of Warcraft TOC", "wowtoc"),
                            ("Wren", "wren"),
                            ("X10", "x10"),
                            ("XML+UL4", "xml+ul4"),
                            ("XQuery", "xquery"),
                            ("XML+Django/Jinja", "xml+django"),
                            ("XML+Ruby", "xml+ruby"),
                            ("XML", "xml"),
                            ("XML+PHP", "xml+php"),
                            ("XML+Smarty", "xml+smarty"),
                            ("Xorg", "xorg.conf"),
                            ("X++", "xpp"),
                            ("XSLT", "xslt"),
                            ("Xtend", "xtend"),
                            ("xtlang", "extempore"),
                            ("YAML+Jinja", "yaml+jinja"),
                            ("YAML", "yaml"),
                            ("YANG", "yang"),
                            ("YARA", "yara"),
                            ("Zeek", "zeek"),
                            ("Zephir", "zephir"),
                            ("Zig", "zig"),
                            ("ANSYS parametric design language", "ansys"),
                            ("IPython", "ipython2"),
                            ("IPython3", "ipython3"),
                            ("IPython console session", "ipythonconsole"),
                        ],
                        default="python",
                        max_length=128,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("abap", "abap"),
                            ("algol", "algol"),
                            ("algol_nu", "algol_nu"),
                            ("arduino", "arduino"),
                            ("autumn", "autumn"),
                            ("bw", "bw"),
                            ("borland", "borland"),
                            ("colorful", "colorful"),
                            ("default", "default"),
                            ("dracula", "dracula"),
                            ("emacs", "emacs"),
                            ("friendly_grayscale", "friendly_grayscale"),
                            ("friendly", "friendly"),
                            ("fruity", "fruity"),
                            ("github-dark", "github-dark"),
                            ("gruvbox-dark", "gruvbox-dark"),
                            ("gruvbox-light", "gruvbox-light"),
                            ("igor", "igor"),
                            ("inkpot", "inkpot"),
                            ("lightbulb", "lightbulb"),
                            ("lilypond", "lilypond"),
                            ("lovelace", "lovelace"),
                            ("manni", "manni"),
                            ("material", "material"),
                            ("monokai", "monokai"),
                            ("murphy", "murphy"),
                            ("native", "native"),
                            ("nord-darker", "nord-darker"),
                            ("nord", "nord"),
                            ("one-dark", "one-dark"),
                            ("paraiso-dark", "paraiso-dark"),
                            ("paraiso-light", "paraiso-light"),
                            ("pastie", "pastie"),
                            ("perldoc", "perldoc"),
                            ("rainbow_dash", "rainbow_dash"),
                            ("rrt", "rrt"),
                            ("sas", "sas"),
                            ("solarized-dark", "solarized-dark"),
                            ("solarized-light", "solarized-light"),
                            ("staroffice", "staroffice"),
                            ("stata-dark", "stata-dark"),
                            ("stata-light", "stata-light"),
                            ("tango", "tango"),
                            ("trac", "trac"),
                            ("vim", "vim"),
                            ("vs", "vs"),
                            ("xcode", "xcode"),
                            ("zenburn", "zenburn"),
                        ],
                        default="friendly",
                        max_length=128,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    )
