from django.db.migrations import writer

MIGRATION_HEADER_TEMPLATE = """\
# Generated by Django %(version)s on %(timestamp)s

"""

writer.MIGRATION_HEADER_TEMPLATE = MIGRATION_HEADER_TEMPLATE


MIGRATION_TEMPLATE = """\
%(migration_header)s%(imports)s

class Migration(migrations.Migration):
    %(replaces_str)s%(initial_str)s%(atomic_str)s%(run_before_str)s

    dependencies = [
        %(dependencies)s\
    ]

    operations = [
        %(operations)s\
    ]
"""

writer.MIGRATION_TEMPLATE = MIGRATION_TEMPLATE
