name: "pre-commit autoupdate"

on:
  schedule:
    - cron: "0 12 * * SUN"  # Every sunday at 12 PM
  # on demand
  workflow_dispatch:

jobs:
  upgrade:
    uses: browniebroke/github-actions/.github/workflows/pre-commit-autoupdate.yml@v1
    secrets:
      gh_pat: ${{ secrets.PRECOMMIT_UPDATE_TOKEN }}
    with:
      config_path: ".pre-commit-config.yaml"
      python_version: "3.12"
